const express = require("express");
const router = express.Router();
const projectController = require("../app/controllers/projectController");
const authUser = require("../middleware/userMiddleware");
const authProj = require("../middleware/projectMiddleware");
//router
router.use(authUser);
router.post("/addProject", projectController.addProject);
router.post("/getProject", projectController.getProject);
router.post("/getAllProject", projectController.getAllProject);
router.post("/getProjectJoined",projectController.getProjectJoined);
router.post("/joinProject", projectController.joinProject);
router.use(authProj);
router.post("/deleteProject", projectController.deleteProject);
router.post("/getPosts", projectController.getPosts);
router.post("/addChat", projectController.addChat);
router.post("/getChat", projectController.getChat);
router.post("/getProjectById", projectController.getProjectById);
router.post("/getUserJoin", projectController.getUserJoin);
module.exports = router;
